# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/PmodOLED_Source/Basys3_Master.xdc

# IP: ip/charLib/charLib.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib}]
