# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.cache/wt [current_project]
set_property parent.project_path /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/charLib.coe
read_mem /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib.mif
read_ip /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib.xco
set_property is_locked true [get_files /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib.xco]

read_verilog -library xil_defaultlib {
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/SpiCtrl.v
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/Delay.v
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OledInit.v
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OledEX.sv
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/PmodOLEDCtrl.v
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib.v
}
read_vhdl -library xil_defaultlib {
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib/simulation/bmg_tb_top.vhd
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib/example_design/bmg_wrapper.vhd
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib/simulation/bmg_tb_pkg.vhd
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib/example_design/charLib_top.vhd
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib/simulation/addr_gen.vhd
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib/simulation/bmg_tb_synth.vhd
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib/simulation/random.vhd
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib/simulation/bmg_stim_gen.vhd
}
read_edif /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/sources_1/ip/charLib/charLib.ngc
read_xdc /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/constrs_1/imports/PmodOLED_Source/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED/OLED.srcs/constrs_1/imports/PmodOLED_Source/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top PmodOLEDCtrl -part xc7k70tfbv676-1
write_checkpoint -noxdef PmodOLEDCtrl.dcp
catch { report_utilization -file PmodOLEDCtrl_utilization_synth.rpt -pb PmodOLEDCtrl_utilization_synth.pb }
