# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED_demo/OLED_demo.cache/wt [current_project]
set_property parent.project_path /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED_demo/OLED_demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/hantaoz3/cs233git/OLED/c:/Users/jsackos/Desktop/Pmod_Demos/In_Progress/PmodOLED/HDL/Verilog_PmodOLED_Demo_Source/PmodOLED/charLib.coe
read_ip /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED_demo/OLED_demo.srcs/sources_1/ip/charLib/charLib.xco
set_property is_locked true [get_files /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED_demo/OLED_demo.srcs/sources_1/ip/charLib/charLib.xco]

read_verilog -library xil_defaultlib {
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/SpiCtrl.v
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/Delay.v
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OledInit.v
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OledEX.v
  /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/PmodOLEDCtrl.v
}
read_xdc /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED_demo/OLED_demo.srcs/constrs_1/imports/PmodOLED_Source/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/hantaoz3/cs233git/OLED/pmodoledctrl_verilog/PmodOLED_Source/OLED_demo/OLED_demo.srcs/constrs_1/imports/PmodOLED_Source/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top PmodOLEDCtrl -part xc7k70tfbv676-1
write_checkpoint -noxdef PmodOLEDCtrl.dcp
catch { report_utilization -file PmodOLEDCtrl_utilization_synth.rpt -pb PmodOLEDCtrl_utilization_synth.pb }
